#!/bin/sh

rm -rvf	src/*.o src/*.so src/symbols.rds \
    	vignettes/auto/ \
	vignettes/*.aux vignettes/*.log vignettes/.out \
        vignettes/*.bbl vignettes/*.blg vignettes/*.pdf \
        vignettes/RcppZiggurat*.tex \
        vignettes/*.tpt vignettes/*.xwm \
        vignettes/jss.bst vignettes/pinp.cls \
        *~ */*~
