#!/bin/sh

rm -rvf	src/*.o src/*.so src/symbols.rds \
    	vignettes/auto/ vignettes/rmd/auto/ \
	vignettes/rmd/*.aux vignettes/rmd/*.log vignettes/rmd/.out \
        vignettes/rmd/*.bbl vignettes/rmd/*.blg vignettes/rmd/*.pdf \
        vignettes/rmd/RcppZiggurat*.tex \
        vignettes/rmd/*.tpt vignettes/rmd/*.xwm \
        vignettes/rmd/jss.bst vignettes/rmd/pinp.cls \
        *~ */*~
