# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

zrnormMT <- function(n) {
    .Call(`_RcppZiggurat_zrnormMT`, n)
}

zsetseedMT <- function(s) {
    invisible(.Call(`_RcppZiggurat_zsetseedMT`, s))
}

zrnormLZLLV <- function(n) {
    .Call(`_RcppZiggurat_zrnormLZLLV`, n)
}

zsetseedLZLLV <- function(s) {
    invisible(.Call(`_RcppZiggurat_zsetseedLZLLV`, s))
}

zrnormV1 <- function(n) {
    .Call(`_RcppZiggurat_zrnormV1`, n)
}

zrnormVecV1 <- function(x) {
    .Call(`_RcppZiggurat_zrnormVecV1`, x)
}

zrnormStlV1 <- function(n) {
    .Call(`_RcppZiggurat_zrnormStlV1`, n)
}

zsetseedV1 <- function(s) {
    invisible(.Call(`_RcppZiggurat_zsetseedV1`, s))
}

zgetseedV1 <- function() {
    .Call(`_RcppZiggurat_zgetseedV1`)
}

zrnorm <- function(n) {
    .Call(`_RcppZiggurat_zrnorm`, n)
}

zrnormVec <- function(x) {
    .Call(`_RcppZiggurat_zrnormVec`, x)
}

zrnormStl <- function(n) {
    .Call(`_RcppZiggurat_zrnormStl`, n)
}

zsetseed <- function(s) {
    invisible(.Call(`_RcppZiggurat_zsetseed`, s))
}

zgetseed <- function() {
    .Call(`_RcppZiggurat_zgetseed`)
}

zgetpars <- function() {
    .Call(`_RcppZiggurat_zgetpars`)
}

zsetpars <- function(p) {
    invisible(.Call(`_RcppZiggurat_zsetpars`, p))
}

zsetseedGSL <- function(s) {
    invisible(.Call(`_RcppZiggurat_zsetseedGSL`, s))
}

zrnormGSL <- function(n) {
    .Call(`_RcppZiggurat_zrnormGSL`, n)
}

zrnormV1b <- function(n) {
    .Call(`_RcppZiggurat_zrnormV1b`, n)
}

zrnormQL <- function(n) {
    .Call(`_RcppZiggurat_zrnormQL`, n)
}

zsetseedQL <- function(s) {
    invisible(.Call(`_RcppZiggurat_zsetseedQL`, s))
}

zrnormGl <- function(n) {
    .Call(`_RcppZiggurat_zrnormGl`, n)
}

zsetseedGl <- function(s) {
    invisible(.Call(`_RcppZiggurat_zsetseedGl`, s))
}

zrnormR <- function(n) {
    .Call(`_RcppZiggurat_zrnormR`, n)
}

ziggbin <- function(nbins, ndraws, generator = "Ziggurat", seed = 42L, edge = 7L, res = 40L) {
    .Call(`_RcppZiggurat_ziggbin`, nbins, ndraws, generator, seed, edge, res)
}

ziggsum <- function(nbins, ndraws, generator = "Ziggurat", seed = 42L) {
    .Call(`_RcppZiggurat_ziggsum`, nbins, ndraws, generator, seed)
}

ziggtest <- function(nbins, ndraws, generator = "Ziggurat", seed = 42L) {
    .Call(`_RcppZiggurat_ziggtest`, nbins, ndraws, generator, seed)
}

