# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

zrnormMT <- function(n) {
    .Call('RcppZiggurat_zrnormMT', PACKAGE = 'RcppZiggurat', n)
}

zsetseedMT <- function(s) {
    invisible(.Call('RcppZiggurat_zsetseedMT', PACKAGE = 'RcppZiggurat', s))
}

zrnormLZLLV <- function(n) {
    .Call('RcppZiggurat_zrnormLZLLV', PACKAGE = 'RcppZiggurat', n)
}

zsetseedLZLLV <- function(s) {
    invisible(.Call('RcppZiggurat_zsetseedLZLLV', PACKAGE = 'RcppZiggurat', s))
}

zrnormV1 <- function(n) {
    .Call('RcppZiggurat_zrnormV1', PACKAGE = 'RcppZiggurat', n)
}

zrnormVecV1 <- function(x) {
    .Call('RcppZiggurat_zrnormVecV1', PACKAGE = 'RcppZiggurat', x)
}

zrnormStlV1 <- function(n) {
    .Call('RcppZiggurat_zrnormStlV1', PACKAGE = 'RcppZiggurat', n)
}

zsetseedV1 <- function(s) {
    invisible(.Call('RcppZiggurat_zsetseedV1', PACKAGE = 'RcppZiggurat', s))
}

zgetseedV1 <- function() {
    .Call('RcppZiggurat_zgetseedV1', PACKAGE = 'RcppZiggurat')
}

zrnorm <- function(n) {
    .Call('RcppZiggurat_zrnorm', PACKAGE = 'RcppZiggurat', n)
}

zrnormVec <- function(x) {
    .Call('RcppZiggurat_zrnormVec', PACKAGE = 'RcppZiggurat', x)
}

zrnormStl <- function(n) {
    .Call('RcppZiggurat_zrnormStl', PACKAGE = 'RcppZiggurat', n)
}

zsetseed <- function(s) {
    invisible(.Call('RcppZiggurat_zsetseed', PACKAGE = 'RcppZiggurat', s))
}

zgetseed <- function() {
    .Call('RcppZiggurat_zgetseed', PACKAGE = 'RcppZiggurat')
}

zrnormgsl <- function(n) {
    .Call('RcppZiggurat_zrnormgsl', PACKAGE = 'RcppZiggurat', n)
}

zrnormV1b <- function(n) {
    .Call('RcppZiggurat_zrnormV1b', PACKAGE = 'RcppZiggurat', n)
}

zrnormql <- function(n) {
    .Call('RcppZiggurat_zrnormql', PACKAGE = 'RcppZiggurat', n)
}

ziggbin <- function(nbins, ndraws, generator = "Ziggurat", seed = 42L, edge = 7L, res = 40L) {
    .Call('RcppZiggurat_ziggbin', PACKAGE = 'RcppZiggurat', nbins, ndraws, generator, seed, edge, res)
}

ziggsum <- function(nbins, ndraws, generator = "Ziggurat", seed = 42L) {
    .Call('RcppZiggurat_ziggsum', PACKAGE = 'RcppZiggurat', nbins, ndraws, generator, seed)
}

ziggtest <- function(nbins, ndraws, generator = "Ziggurat", seed = 42L) {
    .Call('RcppZiggurat_ziggtest', PACKAGE = 'RcppZiggurat', nbins, ndraws, generator, seed)
}

